version: 1.1
orbs:
  maven: circleci/maven@0.0.12
workflows:
  maven_test:
    jobs:
      maven/test:
        build:
          working_directory: ~/tour-api
        docker:
        - image: circleci/openjdk:8-jdk-stretch
        steps:
        - checkout
        - run:
            name: Generate cumulative pom.xml checksum
            command: |
              find . -type f -name "pom.xml" -exec sh -c "sha256sum {} >> ~/pom-checksum.tmp" \;
              sort -o ~/pom-checksum ~/pom-checksum.tmp
            when: always
        - restore_cache:
            key: tour-api-{{ checksum "~/pom-checksum" }}
        - run: mvn dependency:go-offline
        - save_cache:
            paths:
            - ~/.m2
            key: tour-api-{{ checksum "pom.xml" }}
        - run: mvn package
        - store_test_results:
            path: target/surefire-reports
        - store_artifacts:
            path: target/tour-api-0.0.1-SNAPSHOT.jar